#
# Copyright (c) 2025 solarcosmic.
# This project is licensed under the MIT license.
# To view the license, see <https://opensource.org/licenses/MIT>.
#

# The port in which the server runs on. 8080 by default.
port: 8080